const postcssPresetEnv = require('postcss-preset-env')
const flexGapPolyfill = require('flex-gap-polyfill')
// const lost = require('lost')
// const postcssSorting = require('postcss-sorting')

module.exports = {
  plugins: [
    // require('postcss-import'),
    postcssPresetEnv({
      stage: 3,
      features: {
        'nesting-rules': true,
      },
      autoprefixer: {
        flexbox: 'no-2009',
        grid: 'autoplace',
      },
    }),
    flexGapPolyfill({
      only: ['flex-gap'],
    }),
    // lost(),
    // postcssSorting({
    //   order: [
    //     'custom-properties',
    //     'dollar-variables',
    //     'declarations',
    //     'at-rules',
    //     'rules',
    //   ],
    //   'properties-order': [
    //     'display',
    //     'float',
    //     'clear',
    //     'position',
    //     'top',
    //     'right',
    //     'bottom',
    //     'left',
    //     'z-index',
    //     'min-width',
    //     'width',
    //     'min-height',
    //     'height',
    //     'overflow',
    //     'margin',
    //     'margin-top',
    //     'margin-right',
    //     'margin-bottom',
    //     'margin-left',
    //     'padding',
    //     'padding-top',
    //     'padding-right',
    //     'padding-bottom',
    //     'padding-left',
    //     'border',
    //     'border-top',
    //     'border-right',
    //     'border-bottom',
    //     'border-left',
    //     'border-collapse',
    //     'border-spacing',
    //     'background',
    //     'background-color',
    //     'background-image',
    //     'background-position',
    //     'color',
    //     'font',
    //     'text-align',
    //     'vertical-align',
    //     'line-height',
    //     'white-space',
    //     'text-indent',
    //     'text-decoration',
    //     'letter-spacing',
    //     'word-break',
    //     'word-wrap',
    //     'list-style',
    //     'ime-mode',
    //     'content',
    //     'cursor',
    //     'zoom',
    //     'opacity',
    //     'filter',
    //   ],
    //   'unspecified-properties-position': 'bottom',
    // }),
  ],
}
